name: dbt Demo

on:
  workflow_dispatch:

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Verify dbt
        run: dbt --version

      - name: Install packages
        run: dbt deps

      - name: Parse project
        run: dbt parse