name: hello-github-action

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello Github Action"
      - name: Date
        run: date
      - name: List files
        run: ls -ltr