name: Snowflake-github-action-demo

on:
  push:
    branches: 
      - master

jobs:
  snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instal Snowflake CLI
        run: pip install snowflake-cli

      - name: Copy config
        run: |
              mkdir -p ~/.snowflake
              cp .snowflake/connections.toml ~/.snowflake/connections.toml
              chmod 600 ~/.snowflake/connections.toml
              cat ~/.snowflake/connections.toml
      
      - name: execute SQL
        run: |
              snow sql \
              -c snowflake \
              -f sql/01_Insert.sql